### ISSUE TITLE
请问下这个报错是怎么回事

### ISSUE THREAD

**Issue by Bromaomao** [resphinas/claude-on-wechat-master#1]
![1691084755(1)](https://github.com/resphinas/claude-on-wechat-master/assets/115863734/105132d9-78a9-42d9-9ab6-d025ab8b716a)
claude官网能看到回复的消息，就是微信接受不到

**Comment by resphinas** [comment]
claude_api.py  直接运行这个测试脚本试试能不能正常运行 这个运行错误的话 就是你参数填错了

**Comment by resphinas** [comment]
此外另一个可能影响到的问题就是  
claude.py 中第一百行的
      #最大重试次数
      try_time_max = 5
建议改成15
另外请确认填写参数时 org_uuid 是 “3dd“开头的 别填反了，cookie是填写原网页post请求append_message的cookie，先确保claude.py测试脚本能够运行

**Comment by Bromaomao** [comment]
> 这个问题产生的直接原因是 发送信息成功 但是在接受bot返回(官方消息)消息时超时 claude.py 中第一百行 #最大重试次数 try_time_max = 5 建议改成15
> 
> 建议直接运行 claude_api.py 独立测试 文件查看问题所在

直接运行claude_api.py是没问题的，把uuid和cookie复制到config.json过去以后登上微信就收不到消息
![1691125336(1)](https://github.com/resphinas/claude-on-wechat-master/assets/115863734/ca933129-ec6e-4c03-8f3a-43ff3cf9aa2b)

**Comment by Bromaomao** [comment]
> > 这个问题产生的直接原因是 发送信息成功 但是在接受bot返回(官方消息)消息时超时 claude.py 中第一百行 #最大重试次数 try_time_max = 5 建议改成15
> > 建议直接运行 claude_api.py 独立测试 文件查看问题所在
> 
> 直接运行claude_api.py是没问题的，把uuid和cookie复制到config.json过去以后登上微信就收不到消息 ![1691125336(1)](https://user-images.githubusercontent.com/115863734/258299940-ca933129-ec6e-4c03-8f3a-43ff3cf9aa2b.jpg)

另外我也把次数尝试改成了15，依然是这种报错
![1691126255(1)](https://github.com/resphinas/claude-on-wechat-master/assets/115863734/3e6b23f4-4291-4f2e-930c-9910dfbd44e7)

**Comment by resphinas** [comment]
抱歉，有个缺陷一直忘记改，新的con_uuid需要手动把claude_flag.txt这个文件数值改成0，后续我会想办法优化，也可以帮忙想一下，这个文件是用来控制读取最新消息的，但是claude返回的索引有时候是无序的 于是多了这一个消息判断

**Comment by Bromaomao** [comment]
> 抱歉，有个缺陷一直忘记改，新的con_uuid需要手动把claude_flag.txt这个文件数值改成0，后续我会想办法优化，也可以帮忙想一下，这个文件是用来控制读取最新消息的，但是claude返回的索引有时候是无序的 于是多了这一个消息判断

非常感谢，目前可以正常使用了
